### ISSUE TITLE
Not supporting iphone 4s ? 

### ISSUE THREAD

**Issue by twobig** [squarezw/ZWIntroductionViewController#2]
Any idea of that? I have made 3 photos which is particular size for iphone 4s intro, but it seems 3 photo can only swipe for two times, then ends, not even showing the button, it should be the size calculate wrong somehow.
also, how to add another button in your code? if is possible, could you give me some idea how to add one more button, thanks , great work

**Comment by squarezw** [comment]
thanks for you tests, i just updated codes in develop branch, please check out latest code to check that problem was resolved  [link](https://github.com/squarezw/ZWIntroductionViewController/commit/1fe78a8e884dd63e903f6d3e10f91e336924c818)
