### ISSUE TITLE
Positioning completion button

### ISSUE THREAD

**Issue by klauslanza** [squarezw/ZWIntroductionViewController#6]
Is there any way to reposition the completion button to better integrate with the app?

I've tried autolayouting it and setting its frame with no success.

**Comment by squarezw** [comment]
sorry.  currently it could not support autolayouting.  but  there are some other ways you will useful

// vc = ZWIntroductionViewController
1.  set `pageControlOffset` property to control it position
   vc.pageControlOffset = CGPointMake(0, -100);
2. hidden default enter button.  set customize button .

hidden default button
`vc.hiddenEnterButton = true`

put your completion button
`vc.coverView = loginButton`

you could use customized button with any style or layout you want
- please check  "// Example 5 : Advance"  codes in Demo project - 

BTW.  i'll support auto layout ASAP.

**Comment by klauslanza** [comment]
Thanks a lot, loving this lib!

**Comment by squarezw** [comment]
u welcome! 

btw. i just updated the lib(0.3.5) and you could use below codes to easily customize your enter button.

// Setting the button instantly after your init the VC
vc.enterbutton = "Your Button"

**Comment by klauslanza** [comment]
Wow, so fast. Thanks again!
