### ISSUE TITLE
ios 10.2 backgroundImageNames not working

### ISSUE THREAD

**Issue by vitalrum** [squarezw/ZWIntroductionViewController#8]
Hi, i have a problem. 
In your demo project if use 
"self.introductionView = [self coverImagesIntroductionView];"
background imageViews is empty =(
http://joxi.ru/Vm6RbDeConVWmZ

in method "addBackgroundViews" frame is (0,0,0,0)

**Comment by squarezw** [comment]
Thanks for your feedback.  

i have fixed it already on the master branch .  you might fetch that and have a look .
